### ISSUE TITLE
Provide a storage interface with an optional wrapper around doctrine cache

### ISSUE THREAD

**Issue by sagikazarmark** [sobstel/sesshin#1]
I know I was the one who suggested to rely on a specific storage implementation, but it doesn't seem like a good idea now.

The problem is that it is hard to be framework agnostic, because every framework might have it's internal implementation for such storage. Thus until a PSR or something like that is created we should allow people to use their own implementation. So I propose to add back the storage interface with methods based on your need and add a wrapper around doctrine/cache as a default implementation AND suggestion. This would also mean you have to make it a constructor requirement, but that is not such a big problem. In fact, I would be happier to see the most of dependencies in the constructor instead of setters.

**Comment by sobstel** [comment]
`League\Sesshin\Store\StoreInterface` and `League\Sesshin\DoctrineCache` (re-)introduced.

@sagikazarmark, please have a look.

**Comment by sagikazarmark** [comment]
Seems to be good, however I still think that doctrine/cache should entirely be optional even if the implementation is in the core package. I would introduce a factory or a quick setup code which injects the FilesystemCache if needed. Default code like this (using dependencies) has no place in the core class in the age of DI.

**Comment by sobstel** [comment]
I agree it's a bit "controversial" (especially when using DI), but what I promote here is convention over configuration, so you can have it running quickly without additional setup, but adjust it later for your needs (custom store, etc).

As a giva-and-take, what about having in-built File Store and having whole Doctrine\Cache optional? ;-)

**Comment by sagikazarmark** [comment]
Actually my selfish need is to avoid having doctrine/cache as a hard dependency, so any solution that makes it possible is fine for me. ;)

However the point of my previous comment is that you still can have things running quickly by introducing a factory or something like that. It is better because you move this responsibility out of the main class, so if you want to use it at a "lower level" (custom configuration), you don't have to care about the default one. I agree, that a quick setup feature is good and should exist, but not inside the main class.

**Comment by sobstel** [comment]
I fully get your point, but I wanted to balance things (pragmatic vs design pattern freak). And having separate factory looks like over-engineering a bit for me. It does not always make it easier to use.

I could use more words, but following pics explain it a better ;-)
- http://static1.squarespace.com/static/518f5d62e4b075248d6a3f90/t/54687528e4b0768e168b3c76/1416131884224/?format=750w
- http://static1.squarespace.com/static/518f5d62e4b075248d6a3f90/t/54687528e4b0768e168b3c76/1416131884224/?format=750w 

Still I'll make Doctrine\Cache an option only.

**Comment by sobstel** [comment]
Eventually...
- docrine\cache is gone as requirement (just suggested now)
- added FileStore
- made StoreInterface to be required in __construct (after 2nd thought: default store using /tmp directory is not secure on shared hosting anyway, better to do it explicit)

@sagikazarmark let me know if it works for you.

**Comment by sagikazarmark** [comment]
:+1:
