### ISSUE TITLE
Greif, I am afraid that is what I am experiencing with this

### ISSUE THREAD

**Issue by NJseo** [sobstel/sesshin#11]
It all sounds good but following the documentation, I am experiencing issues.

**Comment by NJseo** [comment]
I installed using composer as you instructed. In your directory I created a file myTest.php will the following code:

use Sesshin\Session\User;
use Sesshin\Store\FileStore;

$userSession = new User(new FileStore('src/Store/'));

$userSession->create();
$userSession->login(123);

if ($userSession->isLogged()) {
    $user = UserRepository::find($userSession->getUserId());
    echo sprintf('User %s is logged', $user->getUsername());
}

Made several changes, going back and forth, and still errors.

**Comment by sobstel** [comment]
What errors exactly do you experience?

I can see one error in an example above, should be `Sesshin\User\Session as User` and not `Sesshin\Session\User`.

Also, a file store path (`new FileStore('src/Store/')` in your example) should point to location where session files should be stored (and not session class itself).

**Comment by sobstel** [comment]
No feedback after 1 month. Please re-open if you still have any issues.
