### ISSUE TITLE
Specific usage behavior

### ISSUE THREAD

**Issue by T3chTobi** [sobstel/sesshin#17]
Hi @sobstel ,
I have following questions to the specific usage behavior:

1. Can I set the domain of the session to *.domain.com? (**domain AND subdomains can access the same session**)
 
2. Where should I **put the following settings**? On the first page and then they are active until this session expires?
```
$session->setIdTtl(300);
$session->setIdRequestsLimit(10);
$session->setTtl(1440); ("Session is already opened" Message)
```

3. When the session is for a user who works 8 hours a day with the site, should the Ttl (Time to live) be 8 * 60 * 60? He should login once a day and **the session should last the whole day**.
 
4. Does $session->logout() **delete the session AND the session data** stored inside? Or is it something like session_write_close()?

5. What is the **specific difference** in
`$session->logout()`
`$session->destroy()`
`$session->close()`
and **when to use each one**? (which one to use for a synonym to **session_write_close**, which one for **session logout**)

Is there some link to donate for a coffee?

Thank you VERY MUCH!

**Comment by miketaylor53** [comment]
I would be interested in these questions, too @sobstel and @CodingAnonymous . Would appreciate an answer very much!

**Comment by miketaylor53** [comment]
I would add another coffee for @sobstel for sure!

**Comment by sobstel** [comment]
> Can I set the domain of the session to *.domain.com? (**domain AND subdomains can access the same session**)

Yes. This works all the same as standard PHP session protocol.

> Where should I **put the following settings**? On the first page and then they are active until this session expires?
> 
> ```
> $session->setIdTtl(300);
> $session->setIdRequestsLimit(10);
> $session->setTtl(1440); ("Session is already opened" Message)
> ```

These settings are not persisted alongside a session data, so they need to be configured at code side wherever needed. They need to be called *before* session is opened/created.

It really differs and depends on how your app is structured. For example, you can extract it to some `common.php` file and include it everywhere it's needed, you can have some kind of singleton-like `Registry::getSession` class or - which is probably most common - use some Dependency Injection container and configure it there. 

> When the session is for a user who works 8 hours a day with the site, should the Ttl (Time to live) be 8 * 60 * 60? He should login once a day and **the session should last the whole day**.

Ttl can be basically read as _how many seconds from now_. 

The lib doesn't really support throttling like limiting login to once a day. It's just a time for how long to remember user (store the session).

> Does $session->logout() **delete the session AND the session data** stored inside? Or is it something like session_write_close()?

It just deletes user id from a session. Nothing more. Generally UserSession is very simplistic and it might not be a good fit for many apps (probably better to extend Session on your own).

https://github.com/sobstel/sesshin/blob/master/src/User/Session.php#L52-L55

> What is the **specific difference** in
>    `$session->destroy()`

It completely wipes out (removes) all the data form the session, so it cannot be accessed again. 

https://github.com/sobstel/sesshin/blob/master/src/Session.php#L188-L193

>    `$session->close()`

This one is like `session_write_close`. It saves data, updates last trace, regenerates id (if needed) etc. 

https://github.com/sobstel/sesshin/blob/master/src/Session.php#L167-L183

You don't need to call it explicitly. It's auto-registered with shutdown handler, so it's always executed at the end of the request.

**Comment by T3chTobi** [comment]
Thanks for the great response!

To logout a user and destroy the whole, what of these commands is the safest one or should all three be used in combination?
```
$session->unsetValues();
$session->logout();
$session->destroy();
```

**Comment by sobstel** [comment]
> Thanks for the great response!
> 
> To logout a user and destroy the whole, what of these commands is the safest one or should all three be used in combination?
> 
> ```
> $session->unsetValues();
> $session->logout();
> $session->destroy();
> ```

It depends on your use case, but usually it would be `$session->destroy()`.
