### ISSUE TITLE
Following these best practices, is there any chance of my system being hacked (because of the session)?

### ISSUE THREAD

**Issue by ewertonrfd** [sobstel/sesshin#18]
Hi,
I was left with a doubt:
Following these best practices, is there any chance of my system being hacked (because of the session)?

I already verified that with the php PDO I have already solved failures that my system had

I'm analyzing other things that we use, see if there are flaws, thanks for the feddback right now

**Comment by sobstel** [comment]
There are not known flaws or vulnerabilities in the library. 

Saying that, there's no such a thing as "100% secure". `sesshin` makes it much harder to hack things (eg by not using same session id for unlogged user and logged user later), but sadly doesn't make it impossible. For example, even if you regenerate session id every minute, potential hacker - if he/she manages to hijack session id - still has a minute to do nasty things.

**Comment by ewertonrfd** [comment]
Thanks for the return

And thanks for the alert
The idea is to do as much as possible to help with security!
