### ISSUE TITLE
A few observations

### ISSUE THREAD

**Issue by sagikazarmark** [sobstel/sesshin#2]
Hey, I noticed you updated the code. I have a few observations about some general package things:
1. You could create a better changelog. Check keepachangelog.com for a few advices and examples.
2. There are no newlines between separate structures of the code (php tag, namespace, use, class, etc) which makes it less readable IMO.

Good work, I hope you can make it into the league. Maybe you could ping the owners again.

**Comment by sobstel** [comment]
Thanks for your feedback.

Re. 1. Haven't done proper changelog before. Started only recently.
Re. 2. It's ok with PSR. There are newlines between namespace, use and class though.  Any examples where it's missed?

**Comment by sagikazarmark** [comment]
1. Awesome
2. I didn't mention PSR. It is just readability. Actually I am a bit surprised, because as I remember there were no new line between use and class statements. So either I remember wrong or there is an example which I simply can't find now.
